const C = {
  FETCH_FONTS: 'FETCH_FONTS',
  SET_RANDOM_FONTS: 'SET_RANDOM_FONTS',
  SET_CATEGORY: 'SET_CATEGORY',
  UNSET_CATEGORY: 'UNSET_CATEGORY',
  SET_FONT_COUNT: 'SET_FONT_COUNT',
  ADD_FAVORITE_FONT: 'ADD_FAVORITE_FONT',
  REMOVE_FAVORITE_FONT: 'REMOVE_FAVORITE_FONT'
};

export default C;